Administrator@GTR5900HX MINGW64 /e/SGJQ_Gemini (master)
$ python dashboard_main.py
文件名格式不规范，已跳过: template_xingying.png
Exception in Tkinter callback
Traceback (most recent call last):
  File "E:\SGJQ_Gemini\dashboard_main.py", line 230, in lock_initial_regions
    app_state.locked_regions = regions
NameError: name 'app_state' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\tkinter\__init__.py", line 1892, in __call
__
    return self.func(*args)
  File "E:\SGJQ_Gemini\dashboard_main.py", line 235, in lock_initial_regions
    self.log_to_dashboard(f"[严重错误] 锁定分区时发生错误: {e}", "red")
TypeError: log_to_dashboard() takes 2 positional arguments but 3 were given
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\tkinter\__init__.py", line 1892, in __call
__
    return self.func(*args)
  File "E:\SGJQ_Gemini\dashboard_main.py", line 243, in visualize_regions
    if not app_state.locked_regions:
NameError: name 'app_state' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\tkinter\__init__.py", line 1892, in __call
__
    return self.func(*args)
  File "E:\SGJQ_Gemini\dashboard_main.py", line 243, in visualize_regions
    if not app_state.locked_regions:
NameError: name 'app_state' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\tkinter\__init__.py", line 1892, in __call
__
    return self.func(*args)
  File "E:\SGJQ_Gemini\dashboard_main.py", line 277, in visualize_plus_region
    if not app_state.locked_regions:
NameError: name 'app_state' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\tkinter\__init__.py", line 1892, in __call
__
    return self.func(*args)
  File "E:\SGJQ_Gemini\dashboard_main.py", line 328, in visualize_all_nodes
    if not app_state.locked_regions:
NameError: name 'app_state' is not defined
Exception in Tkinter callback
Traceback (most recent call last):
  File "E:\SGJQ_Gemini\dashboard_main.py", line 230, in lock_initial_regions
    app_state.locked_regions = regions
NameError: name 'app_state' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\tkinter\__init__.py", line 1892, in __call
__
    return self.func(*args)
  File "E:\SGJQ_Gemini\dashboard_main.py", line 235, in lock_initial_regions
    self.log_to_dashboard(f"[严重错误] 锁定分区时发生错误: {e}", "red")
TypeError: log_to_dashboard() takes 2 positional arguments but 3 were given